### ISSUE TITLE
Increased time consumption due to serial execution of code

### ISSUE THREAD

**Issue by tanishqvyas** [rahulmakhija30/brevis#48]
The current implementation is quite slow. It's speed can be increased by employing parallel execution of tasks which aren't interrelated like keywords extraction followed by scraping and summary generation followed by key frame extraction.

**Comment by aniketaayush** [comment]
Added new main and server file which use multiprocessing .Now it uses all the cores on the PC and speeds up all the CPU Bound processes.Hence, the issue is resolved.
