### ISSUE TITLE
Copyright guidelines haven't been reviewed

### ISSUE THREAD

**Issue by tanishqvyas** [rahulmakhija30/brevis#50]
The current implementation makes use of audio and screen thumbnails from a currently existing video which is created by someone else. Thus it is necessary for us to go through the fair use guidelines and copyright act in order to make sure we aren't making any unfair use.

The notes generated (for now) **must include** the credits for the  corresponding content creator. Thus all the information regarding the creator must be added at the end of the notes file so as to give him credits for his work.

**Comment by aniketaayush** [comment]
Copyright Notice is added at the end of the Notes and hence issue is resolved.Currently the changes are present in branch Version 2.0.
