### ISSUE TITLE
The application needs a LOGO

### ISSUE THREAD

**Issue by tanishqvyas** [rahulmakhija30/brevis#53]
There is no official logo present for our application. If someone is willing to take up some kind  of design work then they can go ahead and design a logo for our application.

**Preferred** : Vector graphics

**Comment by Mayank1403** [comment]
Completed Finally!

**Comment by tanishqvyas** [comment]
Good : )



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
01/09/21,
10:17:34
