### ISSUE TITLE
Number of Images extracted according to the length and content of videos are not proper

### ISSUE THREAD

**Issue by aniketaayush** [rahulmakhija30/brevis#83]
The number of images that are currently extracted from a video are NOT proper. Sometimes for a very small video (Flutter) , 25 images are extracted whereas for a 1 hr 5 min video which contains only programming(Much more images should be extracted as video is full of codes on an IDE) only a single image is extracted.

**Comment by aniketaayush** [comment]
Example of such a video(1 hr 5 min and single image extracted) - https://youtu.be/HrBiNHEqSYU

**Comment by himanshujain171** [comment]
Made threshold dynamic. Using video length to set threshold
